Alpha Version
JokeTrue/image-previewer pull request #1
Opened 2020-07-13 18:53 UTC by JokeTrue

2020-07-30 07:00 UTC, Antonboom requested changes
Здравствуйте!
Хорошая работа. Непонятна только копипаста кэша.
Мелкие недочеты обозначил и хотелось бы иметь рабочие тесты. Спасибо.

- [x] Реализован HTTP-сервер, проксирующий запросы к удаленному серверу - 2 балла.
- [x] Реализована нарезка изображений - 2 балла.
- [x] Кэширование нарезанных изображений на диске - 1 балл.
- [x] Ограничение кэша по месту (LRU кэш) - 1 балл.
- [x] Прокси сервер правильно передает заголовки запроса - 1 балл.
- [ ] Написаны интеграционные тесты - 3 балла.
- [ ] Тесты адекватны и полностью покрывают фукнционал - 1 балл.
- [ ] Проект возможно собрать чере `make build`, запустить через `make run`
  и протестировать через `make test` - 1 балл.
- [ ] Понятность и чистота кода - до 3 баллов.

9 / 15

2020-07-30 07:00 UTC, Antonboom commented on cmd/main.go
> +		defer os.RemoveAll(*cacheDir)
логируем все ошибки
```golang
defer func() {
    if err := os.RemoveAll(*cacheDir); err != nil {
        logger.Error(...)
    }
}
```

2020-07-30 07:00 UTC, Antonboom commented on cmd/main.go
> +	cacheDir        = flag.String("cache-dir", "", "Path to Cache dir")
если использовать `flag.StringP(&cacheDir)` (и пр.), то потом можно просто работать с переменной, не с указателем (удобней без звездочек)

2020-07-30 07:00 UTC, Antonboom commented on pkg/cache/cache.go
> +package cache
если это копипаста кэша из
https://github.com/hashicorp/golang-lru

то может его и будете использовать как модуль?

2020-07-30 07:00 UTC, Antonboom commented on pkg/cache/cache_test.go
> +package cache
тесты копипаста или вроде свои?))

2020-07-30 07:00 UTC, Antonboom commented on pkg/service/service.go
> +	return <-sig
signal.Stop

2020-07-30 07:00 UTC, Antonboom commented on pkg/fetcher/fetcher.go
> +	if resp.Header.Get("Content-type") != "image/jpeg" {
"image/jpeg" в константы?

нет кстати случаем готовых

2020-07-30 07:00 UTC, Antonboom commented on pkg/logging/context.go
> +		oldFields, _ := val.(Fields)
тут можно проверить ok и кинуть панику 
(своеобразный assert на правильную реализацию)

вообще по возможности не оставлять ошибки и ok-проверки без внимания

2020-07-30 07:00 UTC, Antonboom commented on pkg/logging/context.go
> +		newFields = make(Fields)
make(Fields, len(oldFields) + len(fields))

2020-07-30 07:00 UTC, Antonboom commented on pkg/logging/logger.go
> +type Level uint32
достаточно просто int

2020-07-30 07:00 UTC, Antonboom commented on pkg/lru/lru.go
> +package lru
аналогично, полная копипаста
https://github.com/hashicorp/golang-lru/tree/master/simplelru

зачем?

2020-07-30 07:00 UTC, Antonboom commented on pkg/transformer/transformer.go
> +// nolint
указать конкретный линтер

2020-07-30 07:00 UTC, Antonboom commented on pkg/utils/utils.go
> +func GetMD5Hash(text string) string {
при желании для некриптографического использования можно взять хэш побыстрее

2020-07-30 07:00 UTC, Antonboom commented on pkg/app/application.go
> +		rawWidth, rawHeight := params.Get("width"), params.Get("height")
не соответствует ТЗ: query-параметры вместо path-параметров

2020-07-30 07:00 UTC, Antonboom commented on cmd/main.go
> +	"flag"
импорты поехали

2020-07-30 07:00 UTC, Antonboom commented on pkg/transformer/transformer.go
> +	src = imaging.Fill(src, width, height, imaging.Center, imaging.Lanczos)
повезло найти библиотеку :)
не смотрели, как внутри работает?

2020-07-30 07:00 UTC, Antonboom commented on tests/image_previewer_test.go
> +	assert.NoError(t, err)
смесь assert и require

2020-07-30 07:00 UTC, Antonboom commented on tests/image_previewer_test.go
> +	assert.True(t, len(body) > 0)
а где проверка, что получили нужный размер?

2020-07-30 07:00 UTC, Antonboom commented on tests/image_previewer_test.go
> +	assert.True(t, len(body) > 0)
require.Len

2020-07-30 07:00 UTC, Antonboom commented on tests/image_previewer_test.go
> +package tests
это обычные интеграционные тесты, не BDD 
(про `make bdd`, лучше тогда `make integration-tests`)

2020-07-30 07:00 UTC, Antonboom commented on tests/image_previewer_test.go
> +import (
у меня не работает :(

```
▶ make bdd            
docker-compose -f ./docker-compose-tests.yaml up --abort-on-container-exit --exit-code-from integration-tests && \
        docker-compose -f ./docker-compose-tests.yaml down
Pulling nginx (nginx:alpine)...
alpine: Pulling from library/nginx
cbdbe7a5bc2a: Already exists
85434292d1cb: Pull complete
75fcb1e58684: Pull complete
2a8fe5451faf: Pull complete
42ceeab04dd4: Pull complete
Digest: sha256:ee8c35a6944eb3cc415cd4cbeddef13927895d4ffa50b976886e3abe48b3f35a
Status: Downloaded newer image for nginx:alpine
Pulling integration-tests (golang:1.14)...
1.14: Pulling from library/golang
31dd5ebca5ef: Pull complete
3ed641c4ae98: Pull complete
bcd57146431e: Pull complete
ac34a4d7c330: Pull complete
e3faf675e54f: Pull complete
6dce2b085ae0: Pull complete
3d864a24b2ed: Pull complete
Digest: sha256:2aa6447d32de9bd2156c5aa379acb2766c196415626d06d8f5fcc2167e6f8844
Status: Downloaded newer image for golang:1.14
Recreating image-previewer       ... done
Creating image-previewer_nginx_1 ... done
Creating image-previewer_integration-tests_1 ... done
Attaching to image-previewer, image-previewer_nginx_1, image-previewer_integration-tests_1
image-previewer      | WARNING: no logs are available with the 'none' log driver
nginx_1              | WARNING: no logs are available with the 'none' log driver
integration-tests_1  | go: downloading github.com/stretchr/testify v1.6.1
integration-tests_1  | go: downloading github.com/pmezard/go-difflib v1.0.0
integration-tests_1  | go: downloading gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
integration-tests_1  | go: downloading github.com/davecgh/go-spew v1.1.1
integration-tests_1  | === RUN   TestFill
integration-tests_1  | --- PASS: TestFill (0.05s)
integration-tests_1  | === RUN   TestServerDoesntExist
integration-tests_1  |     image_previewer_test.go:71: 
integration-tests_1  |          Error Trace:    image_previewer_test.go:71
integration-tests_1  |          Error:          Not equal: 
integration-tests_1  |                          expected: 502
integration-tests_1  |                          actual  : 500
integration-tests_1  |          Test:           TestServerDoesntExist
integration-tests_1  | --- FAIL: TestServerDoesntExist (0.03s)
integration-tests_1  | === RUN   TestCropNotImage
integration-tests_1  |     image_previewer_test.go:84: 
integration-tests_1  |          Error Trace:    image_previewer_test.go:84
integration-tests_1  |          Error:          Not equal: 
integration-tests_1  |                          expected: 502
integration-tests_1  |                          actual  : 500
integration-tests_1  |          Test:           TestCropNotImage
integration-tests_1  | --- FAIL: TestCropNotImage (0.02s)
integration-tests_1  | === RUN   TestURLWrongScheme
integration-tests_1  |     image_previewer_test.go:97: 
integration-tests_1  |          Error Trace:    image_previewer_test.go:97
integration-tests_1  |          Error:          Not equal: 
integration-tests_1  |                          expected: 502
integration-tests_1  |                          actual  : 500
integration-tests_1  |          Test:           TestURLWrongScheme
integration-tests_1  | --- FAIL: TestURLWrongScheme (0.00s)
integration-tests_1  | FAIL
integration-tests_1  | FAIL     github.com/JokeTrue/image-previewer/tests       0.102s
integration-tests_1  | FAIL
image-previewer_integration-tests_1 exited with code 1
Aborting on container exit...
Stopping image-previewer                     ... done
Stopping image-previewer_nginx_1             ... done
make: *** [bdd] Error 1
```

2020-07-30 07:02 UTC, JokeTrue commented on pkg/cache/cache_test.go
> +package cache
Адаптированные

2020-07-30 07:06 UTC, JokeTrue commented on pkg/app/application.go
> +		rawWidth, rawHeight := params.Get("width"), params.Get("height")
@Antonboom
А в чем принципиальная разница?
Если это микросервис с одной единственный функцией, то какой смысл делать какой-то url отличный от "/"?
Мне кажется это более чистым подходом с точки зрения реализации.

2020-08-16 12:23 UTC, Antonboom approved these changes
Спасибо за работу!

Принято
13 / 15

2020-08-16 12:23 UTC, Antonboom commented on pkg/app/application.go
> +		rawWidth, rawHeight := params.Get("width"), params.Get("height")
Разница в том, что если проксируемый URL содержит query-параметры, то вы не отличите их от своих.

2020-08-16 12:23 UTC, Antonboom commented on tests/image_previewer_test.go
> +	width, height := 333, 666
напрашивается табличный тест на набор различных ширин-высот

2020-08-17 05:55 UTC, closed without merging